<?php
include("./../connection.php");
//TODO: OBTENER EL EMAIL DE PAGES/AUTHENTIFICATION/RESETPASWORD.PHP SE REVISAN SI ESE CORREO ESTA REGISTRADO EN LA BD Y SI ESTA ENVIA UN EMAIL CON EL LINK A PAGES/AUTHENTIFICATION/NEWPASSWORD.HTML TIENE QUE TIRAR UNA ALERTA TIPO SUCCES CUANDO ENVIE EL MAIL DICIENDO QUE REVISE SU CORREO Y AL HACER ESTO ESTA PROGRAMADO PARA QUE VAYA AL LOGIN 
$msg = ['type' => 'success', 'text' => 'recuperar contraseña'];
sendJson(null, $msg, null, null, null);
