<?php
include("./../connection.php");
$dni = getInputValue($_POST['tramitNumber'], ' El dni', 8, 'integer', 8);
$cuilFirstCharacters = getInputValue($_POST['cuilFirstCharacters'], 'La primera parte del  CUIL', 2, 'integer', 2);
$cuilLastCharacters = getInputValue($_POST['cuilLastCharacters'], 'La ultima parte del  CUIL', 1, 'integer', 1);
$cuil = $cuilFirstCharacters . $dni . $cuilLastCharacters;
$name = $_POST['name'];
$surname = $_POST['surname'];
$dateBirth = $_POST['dateBirth'];
$gender = setSelectValue($_POST['gender']);
$phone = $_POST['phone'];
$email = $_POST['email'];
$address = $_POST['address'];
$addressNumber = $_POST['addressNumber'];
$location = setSelectValue($_POST['location']);
$id = getMd5Id("PERSONAL_INFORMATION", "ID_DNI");
//Revisa si ya hay un registro con los datos del paciente registrado;
$sql = "SELECT COUNT(*) AS numberOfMatches FROM `PERSONAL_INFORMATION` WHERE `tramit_nume` = ?";
$typeOfParameters = "i";
$parameters = array($cuil);
$result = getPreparedStatement($sql, $typeOfParameters, $parameters);
$data =  getResultOfPreparedStatement($result);
setMessageOfDuplicateRecord($data, 'un paciente');
$sql = "INSERT INTO `PERSONAL_INFORMATION`( `ID_DNI`,`dni`,`tramit_nume`,`name`,`surname`,`gender`,`date_Birth`,`phone`,`email`,`address`,`address_number`,`PK_ID_LOCATION`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
$typeOfParameters = "siissssissii";
$parameters = array($id, $dni, $cuil, $name, $surname, $gender, $dateBirth, $phone, $email, $address, $addressNumber, $location);
$result = getPreparedStatement($sql, $typeOfParameters, $parameters);
sendJson(null, $msg, $id, null, null);
